# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: Syrian Refugee Outreach Program
subtitle: A universal training protocol to help train people to fit prosthetics. This is the documentation of an on-going project - which will be completed on May 8th.

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/syrianrefugee'

# Author/Organization info to be displayed in the templates
author:
  name: Weiwei Hsu
  url: http://www.weiweihsu.com

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ./
  internal: true
- text: Research
  url: research/
  internal: true
- text: Synthesis
  url: synthesis/
  internal: true
- text: Process
  url: process/
  internal: true

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: DOCter
  description: Jekyll template for docs
  url: https://github.com/cfpb/DOCter

# Style Variables
brand_color: "#30228e"

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1

# Ideal image slider
iis_slider_array: []

gems:
  -octopress-video-tag
